Pocket/shareable-lists-api

schema-public.graphql, src/database/types.ts
`Status` by default is always `PRIVATE` when creating a `List`, so removing `Status` from the body.
- [https://getpocket.atlassian.net/browse/OSL-198](https://getpocket.atlassian.net/browse/OSL-198)
=> OSL-198: removing `status` from `CreateShareableListInput`

src/admin/server.ts, src/public/server.ts
Turning off the formatter for now as the web team needs to get the errors unmasked.
[OSL-202](https://getpocket.atlassian.net/browse/OSL-202) needs to get done in order to turn back on the formatter.
[OSL-202]: https://getpocket.atlassian.net/browse/OSL-202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NO-TICKET: Turning off the error formatter

src/admin/server.ts, src/public/server.ts
Due to the investigation on Apollo errors getting masked, it is determined it is a gateway level issue, so turning the apollo utils errorFormatter back on.
=> NO-TICKET: turning the apollo utils errorFormatter back on

schema-public.graphql, src/database/mutations.ts, src/database/mutations/ShareableList.ts, src/database/queries/ShareableList.ts, src/database/types.ts, src/public/resolvers/fieldResolvers.ts, src/public/resolvers/fragments.gql.ts, src/public/resolvers/index.ts, src/public/resolvers/mutations/ShareableList.integration.ts, src/public/resolvers/mutations/ShareableList.ts, src/public/resolvers/mutations/sample-mutations.gql.ts, src/public/resolvers/queries/ShareableList.integration.ts, src/public/resolvers/queries/sample-queries.gql.ts, src/test/helpers/createShareableListHelper.ts
Unblock the Web team by adding another mutation to the public graph.
- Added the mutation and integration tests.
- Updated `createShareableListHelper` to no longer generate slugs as they need to be set on publishing the list, not on initial list creation.
- Updated existing tests to cater for that.
- Refactored queries and mutations used in integration tests to use fragments to make sure each operation consistently returns all public values for lists and list items.
- Whether I've covered all edge cases both in code and tests.
- https://getpocket.atlassian.net/browse/OSL-102
=> feat(mutation): [OSL-102] Add `updateShareableList` mutation

schema-public.graphql, src/database/queries.ts, src/database/queries/ShareableList.ts, src/public/resolvers/fragments.gql.ts, src/public/resolvers/index.ts, src/public/resolvers/queries/ShareableList.integration.ts, src/public/resolvers/queries/ShareableList.ts, src/public/resolvers/queries/sample-queries.gql.ts
* Added the `shareableLists` query to the public schema (returns an array of Lists for a `userId` passed via the headers). This will unblock the web team and allow them to retrieve an array of Lists for a user.
* Implemented the db query and `orderBy: { updatedAt: 'desc' }`
* Implemented the resolver
* Added integration tests
* Removed the temporary `lists` query and dummy data
- [https://getpocket.atlassian.net/browse/OSL-97](https://getpocket.atlassian.net/browse/OSL-97)
=> OSL-97: Adding shareableLists query & resolver & integration tests

schema-public.graphql, src/database/mutations.ts, src/database/mutations/ShareableListItem.ts, src/public/resolvers/index.ts, src/public/resolvers/mutations/ShareableList.ts, src/public/resolvers/mutations/ShareableListItem.integration.ts, src/public/resolvers/mutations/ShareableListItem.ts, src/public/resolvers/mutations/sample-mutations.gql.ts, src/public/resolvers/mutations/utils.ts, src/public/resolvers/queries/sample-queries.gql.ts, src/test/helpers/createShareableListHelper.ts
* Added `deleteShareableListItem` mutation to public schema along with the resolver and tests
* A `ListItem` cannot be deleted if its parent `List` `moderationStatus` = `HIDDEN`
- [https://getpocket.atlassian.net/browse/OSL-151](https://getpocket.atlassian.net/browse/OSL-151)
=> OSL-151: Adding deleteShareableListItem mutation, resolver & tests

.circleci/config.yml, schema-admin.graphql, schema-public.graphql, schema-shared.graphql, src/typeDefs.ts
* Created admin api schema with `ShareableList` model
* included fields `id`, `userId`, `moderatedBy`, `moderationReason`
* removed `listItems` fields
* Created `schema-shared.graphql` and moved `ShareableListStatus` and `ShareableListModerationStatus` to the shared schema
* Updated the Apollo job in CircleCI to append shared schema to both graphs & check & publish the admin api schema
- [https://getpocket.atlassian.net/browse/OSL-153](https://getpocket.atlassian.net/browse/OSL-153)
=> OSL-153: Adding admin api schema and configuring CircleCI Apollo job

prisma/schema.prisma, schema-public.graphql, src/database/mutations.ts, src/database/mutations/ShareableList.ts, src/public/resolvers/index.ts, src/public/resolvers/mutations/ShareableList.integration.ts, src/public/resolvers/mutations/ShareableList.ts, src/public/resolvers/mutations/sample-mutations.gql.ts
Adding a delete API call for Shared Lists, and related tests.
This PR implements the basic List delete. Deletes are currently "hard" I expect that these will need to become soft deletes when data retention policy is clear, and when opportune.
List Items will need to be deleted when a list is deleted (presumably) this is ticketed at [OSL-124](https://getpocket.atlassian.net/browse/OSL-214?atlOrigin=eyJpIjoiMzdlMTVmM2FhODlmNDIwMDliZDUzYzM2ZTgyYWE4MTkiLCJwIjoiamlyYS1zbGFjay1pbnQifQ) and will be address in a follow-on PR.
- How are app metrics/observability handled? 
- How is input sanitization handled?
I didn't see any evidence of these in the codebase, so wondering where these are handled and how they work, to whatever extent they are materialized.
There should be no outstanding deployment …
=> feat(mutation): [OSL-112] Add deleteShareableList mutation

src/database/mutations/ShareableList.ts, src/database/mutations/ShareableListItem.ts, src/shared/constants.ts
As discussed in the previous[ PR](https://github.com/Pocket/shareable-lists-api/pull/51), we will update the existing `deleteShareableListItem` mutation to handle the rare yet possible Prisma `RECORD NOT FOUND` error.
- [https://getpocket.atlassian.net/browse/OSL-223](https://getpocket.atlassian.net/browse/OSL-223)
=> OSL-223: update deleteShareableListItem mutation

schema-public.graphql, src/database/mutations/ShareableListItem.ts, src/database/types.ts, src/public/resolvers/fragments.gql.ts, src/public/resolvers/mutations/ShareableListItem.integration.ts, src/test/helpers/createShareableListItemHelper.ts
* Added `itemId` as optional input param for `createShareableList` mutation
* Added `itemId` to `ShareableListItem` type in public schema
- [https://getpocket.atlassian.net/browse/OSL-224](https://getpocket.atlassian.net/browse/OSL-224)
=> OSL-224: adding itemId as query input param for createShareableList mutation

src/database/mutations/ShareableList.ts, src/database/mutations/ShareableListItem.ts, src/public/resolvers/mutations/ShareableList.integration.ts
Delete list items when deleting a list.
This PR is pretty straightforward, but it did raise questions wrt Pocket's usage of foreign keys, commented inside.
- Link to JIRA tickets
[OSL-214](https://getpocket.atlassian.net/browse/OSL-214)
Followed existing patterns. Would have preferred to not make list deletion subject to list item deletion but this is forced by key constraints at present. Also, we could arguably use to have integration tests directly against the mutations. There were not there at present, so I skipped this and tested on the public route where `deleteAllListItemsForList` is used instead. 
[OSL-214]: https://getpocket.atlassian.net/browse/OSL-214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(mutation): [OSL-214] Delete list items when deleting a list

src/database/mutations/ShareableList.ts, src/public/resolvers/mutations/ShareableList.integration.ts
* Ensuring generated slug for a list first time made public is unique. Adding a consecutive number to generated slug based on # of slugs containing list title in db.
* Added edge test case.
- [https://getpocket.atlassian.net/browse/OSL-228](https://getpocket.atlassian.net/browse/OSL-228)
=> OSL-228: ensuring generated slug is unique

prisma/migrations/20230228225212_add_publisher_to_list_items/migration.sql, prisma/schema.prisma, schema-public.graphql, src/database/mutations/ShareableListItem.ts, src/database/types.ts, src/public/resolvers/fragments.gql.ts, src/public/resolvers/mutations/ShareableListItem.integration.ts, src/public/resolvers/queries/ShareableList.integration.ts, src/test/helpers/createShareableListItemHelper.ts
Unblock the frontend as they need to save and display the `publisher` field on stories added to shareable lists.
- Added `publisher` field to Prisma schema.
- Added `publisher` to list of props on the `ShareableListItem` type in the public schema and to `CreateShareableListItemInput` to take in that value from the frontend when a new list item is created.
- Updated tests and test helpers to test for the presence of this field everywhere list items are manipulated or returned.
https://getpocket.atlassian.net/browse/OSL-240
=> feat(list items): [OSL-240] Add `publisher` field to List Items

src/database/mutations/ShareableList.ts, src/public/resolvers/mutations/ShareableList.integration.ts
Enforce list title and description length during list update. Updated tests.
- [https://getpocket.atlassian.net/browse/OSL-245](https://getpocket.atlassian.net/browse/OSL-245)
=> OSL-245: enforce list title and description length during list update

src/admin/resolvers/queries/ShareableList.ts, src/database/mutations/ShareableList.ts, src/database/mutations/ShareableListItem.ts, src/public/context.ts, src/public/resolvers/mutations/ShareableList.integration.ts, src/public/resolvers/mutations/ShareableListItem.integration.ts
use `NOT_FOUND` error to obfuscate potential malicious API request responses. (better if an attacker doesn't know that the list / list item ID they are maliciously trying to manipulate is valid.)
- https://getpocket.atlassian.net/browse/OSL-206
=> refactor(errors): use NOT_FOUND in more places for security

.github/workflows/unit-tests.yml, package-lock.json, package.json, src/public/resolvers/mutations/ShareableList.integration.ts, src/public/resolvers/mutations/ShareableListItem.integration.ts, src/public/resolvers/mutations/utils.spec.ts, src/public/resolvers/mutations/utils.ts
Sanitize all inputs! 
- Added the `xss` package.
- Added a new util function that sanitises inputs & added usage of it through the `executeMutation` function.
- Added a new GitHub workflow to run a check over unit tests.
- Modified existing integration tests to add checks for sanitization.
- https://getpocket.atlassian.net/browse/OSL-227
=> feat(sanitization): [OSL-227] add XSS protection to all public mutations

schema-public.graphql, src/database/queries.ts, src/database/queries/PilotUser.ts, src/database/queries/ShareableList.ts, src/public/resolvers/index.ts, src/public/resolvers/queries/PilotUser.integration.ts, src/public/resolvers/queries/PilotUser.ts, src/public/resolvers/queries/sample-queries.gql.ts, src/test/helpers/cleardb.ts, src/test/helpers/createPilotUserHelper.ts, src/test/helpers/index.ts
add a basic query to know if the `userId` passed in the header is a part of the pilot program.
- removed unnecessary async declarations
- https://getpocket.atlassian.net/browse/OSL-248
removed `async` declarations on functions that have no `await` calls. (i don't think this has any performance impact either way, but it's not needed.)
=> feat(isPilotUser query): query to know if user is in pilot program

src/database/mutations/ShareableList.ts, src/public/resolvers/mutations/ShareableList.integration.ts
fix a bug where sending the list's current title value to `updateShareableList` would cause a "duplicate title" error.
- [Slack thread](https://pocket.slack.com/archives/C04HWMUKLN5/p1677865852780239)
- https://getpocket.atlassian.net/browse/OSL-251
=> fix(list title update): sending existing title should not fail

schema-public.graphql, src/database/mutations/ShareableList.ts, src/database/types.ts, src/public/resolvers/mutations/ShareableList.integration.ts, src/public/resolvers/mutations/ShareableList.ts, src/public/resolvers/mutations/sample-mutations.gql.ts
According to t[his slack thread](https://pocket.slack.com/archives/C04HWMUKLN5/p1677691820523829), we want to have the option to create a `ShareableListItem` when creating a `ShareableList`. Updating the `createShareableList` mutation to take in an optional `listItemData` param.
- [https://getpocket.atlassian.net/browse/OSL-243](https://getpocket.atlassian.net/browse/OSL-243)
=> OSL-243: add listItemData param to createShareableList mutation

src/public/resolvers/fragments.gql.ts, src/public/resolvers/mutations/ShareableList.integration.ts
Fix a bug + improve test coverage so that it doesn't happen again.
- Updated sample fragment for lists to retrieve `userId` so that it has a full list of returned fields.
- Updated tests to assert `userId` is returned as a result of the update mutation.
- https://getpocket.atlassian.net/browse/OSL-255
=> fix(mutation): [OSL-255] retrieving userId from updateShareableList mutation should not throw error

src/database/queries/PilotUser.ts, src/public/resolvers/mutations/ShareableList.integration.ts, src/public/resolvers/mutations/ShareableListItem.integration.ts, src/public/resolvers/queries/PilotUser.integration.ts, src/public/resolvers/queries/PilotUser.ts, src/public/resolvers/queries/ShareableList.integration.ts, src/public/resolvers/queries/ShareableList.ts, src/public/resolvers/utils.ts
validate the `userId` in headers is in the pilot user group. applies to all public API endpoints _except_ `shareableListPublic`.
- standardize integration test error checking
- https://getpocket.atlassian.net/browse/OSL-196
=> feat(API authorization): validate pilot user on necessary API calls

src/database/queries/ShareableList.ts, src/public/resolvers/queries/ShareableList.integration.ts
This [slack thread](https://pocket.slack.com/archives/C04HWMUKLN5/p1678725002822039) informs that the `shareableListPublic` query returns both `PRIVATE` and `PUBLIC` list. This PR updates the query to return only a `PUBLIC` list.
- [https://getpocket.atlassian.net/browse/OSL-263](https://getpocket.atlassian.net/browse/OSL-263)
=> OSL-263: shareableListPublic query should not return PRIVATE list

schema-public.graphql, schema-shared.graphql, src/public/resolvers/fragments.gql.ts, src/public/resolvers/index.ts, src/public/resolvers/mutations/ShareableList.integration.ts, src/public/resolvers/queries/ShareableList.integration.ts, src/shared/resolvers/fields/User.ts
resolve federated User entity.
- necessary to display user information on public lists
- remove userId from ShareableList in API (as user is now available)
[successfully pushed to dev](https://app.circleci.com/pipelines/github/Pocket/shareable-lists-api/498/workflows/dc76973e-97fc-443c-bf2a-6e5ec3226315).
- https://getpocket.atlassian.net/browse/OSL-266
=> feat(User): resolve federated User entity

src/config/index.ts, src/database/mutations/ShareableList.ts, src/public/resolvers/mutations/ShareableList.integration.ts
Improve slugs for shared lists.
- Updated `slugify` config to remove all characters that don't exist in the package's char map: https://github.com/simov/slugify/blob/master/config/charmap.json
- Added a neutral slug text for cases when list title is composed entirely of emoji or other characters that would be removed during the slugifying process: `shared-list`.
- Added two new integration tests to cover updated functionality.
https://getpocket.atlassian.net/browse/OSL-312
=> chore(validation): [OSL-312] Remove emoji from list slugs

src/admin/resolvers/queries/ShareableList.ts
Improve the error message for `searchShareableList` query - initially it was set up in a not-so-UX-friendly way and showed up as `[GraphQL error]: Error - Not Found: abcd123`. This is related to OSL - 167 (the frontend tools moderation ticket).
=> chore(errors): Improve error message copy for admin query

prisma/seed.ts, src/database/mutations/ShareableList.ts
Improve ease of Admin Tools development for Shareable Lists.
- Update seed script to make lists public
- And have slugs generated for them so that they can be used in Dev Curation Admin Tools for testing and development
- not ticketed, but related to OSL - 167
=> chore(test data): Update seed script to make lists public

schema-public.graphql, schema-shared.graphql, src/database/mutations/ShareableList.ts, src/database/mutations/ShareableListItem.ts, src/database/types.ts, src/public/resolvers/mutations/ShareableList.integration.ts, src/public/resolvers/mutations/ShareableListItem.integration.ts, src/public/resolvers/utils.spec.ts, src/public/resolvers/utils.ts
change `itemId` in the API to an `ID`.
- necessary to support clients, who treat itemId as string due to legacy issues
- https://getpocket.atlassian.net/browse/OSL-333
- failing the entire operation when trying to create a list w/a list item with an invalid id. this seems like the easiest route, as it's not straightforward to create the list successfully but fail the list item. would be happy to find a better way here (create the list and return that data while also returning the error for the list item), but this is an edge case that i'm not sure needs more time devoted to it.
=> refactor(itemId): change itemId to ID (string) from Float

src/database/mutations/ShareableListItem.ts, src/public/resolvers/queries/ShareableList.integration.ts, src/shared/resolvers/fields/PrismaBigInt.ts, src/test/helpers/createShareableListItemHelper.ts
fix resolving when itemId is null in the db.
[successfully pushed to dev](https://app.circleci.com/pipelines/github/Pocket/shareable-lists-api/818/workflows/6f32e29e-11be-43a4-9e45-3522b3ec699a) and verified with an `itemId = null` scenario.
- https://getpocket.atlassian.net/browse/OSL-337
=> fix(itemId): fix resolving when itemId is null in the db

src/snowplow/events.spec.ts, src/snowplow/events.ts, src/snowplow/types.ts
Analytics updated `slug` field to be optional on `shareable_list` entity. Updating `slug` field to be optional on Snowplow ShareableList type.
- [https://getpocket.atlassian.net/browse/OSL-339](https://getpocket.atlassian.net/browse/OSL-339)
=> OSL-339: Make slug optional on Snowplow ShareableList type

src/snowplow/events.spec.ts, src/snowplow/events.ts, src/snowplow/types.ts
Sending `userId` as part of the ShareableList entity to Snowplow. As per [this request](https://pocket.slack.com/archives/CR6T8BNCT/p1680652916308989).
- [https://getpocket.atlassian.net/browse/OSL-388](https://getpocket.atlassian.net/browse/OSL-388)
=> OSL-388: Add userId to ShareableList Snowplow type

prisma/migrations/20230404181758_adjust_item_id_field/migration.sql, prisma/schema.prisma, src/database/mutations/ShareableListItem.ts, src/public/resolvers/queries/ShareableList.integration.ts, src/public/resolvers/utils.spec.ts, src/public/resolvers/utils.ts, src/shared/resolvers/fields/PrismaBigInt.ts, src/shared/resolvers/fields/sharedResolversFields.spec.ts, src/test/helpers/createShareableListItemHelper.ts
`itemId` field has been backfilled now, so the field can be enforced to be required on the Prisma level. Cleaned up some code for passing a null `itemId`.
- [https://getpocket.atlassian.net/browse/OSL-371](https://getpocket.atlassian.net/browse/OSL-371)
=> OSL-371: Enfore itemId to be required at Prisma level

prisma/migrations/20230407161316_add_note_visibility_to_list/migration.sql, prisma/schema.prisma, prisma/seed.ts, src/admin/resolvers/queries/ShareableList.integration.ts, src/database/mutations/ShareableList.ts, src/database/queries/ShareableList.ts, src/database/types.ts, src/public/resolvers/mutations/ShareableList.integration.ts, src/public/resolvers/queries/ShareableList.integration.ts, src/snowplow/events.spec.ts, src/snowplow/types.ts, src/test/helpers/createShareableListHelper.ts, src/test/helpers/updateShareableListHelper.ts
add list item note visibility control to list entity.
- backfills existing rows to have PRIVATE visibility
[successfully deployed to dev](https://app.circleci.com/pipelines/github/Pocket/shareable-lists-api/942/workflows/9e331cff-bd17-4b32-be3f-38d019d28d03) (also manually verified db integrity/data).
- https://getpocket.atlassian.net/browse/OSL-394
renamed the prisma enum `ListStatus` to the more general `Visibility` for semantic re-use here.
=> feat(note visibility): add list item note visibility control to list

schema-admin.graphql, schema-public.graphql, schema-shared.graphql, src/database/types.ts, src/public/resolvers/mutations/ShareableList.integration.ts, src/public/resolvers/queries/ShareableList.integration.ts, src/shared/fragments.gql.ts, src/snowplow/events.spec.ts, src/test/helpers/createShareableListHelper.ts
add `listItemNoteVisibility` field to the API
- small refactor of some tests
- renamed `ShareableListStauts` graph enum to `ShareableListVisibility`
verified with web team that the enum rename is safe on their end (they only use the values, which aren't changing).
- https://getpocket.atlassian.net/browse/OSL-395
=> feat(listItemNoteVisibility): add field to the API

package-lock.json, package.json, src/public/routes/deleteUserData.integration.ts, src/public/routes/deleteUserData.ts
Legal said we don't need to retain any data. When a user deletes their account, `/deleteUserData` endpoint will delete all shareable list data from the db for that user. Added integration test for `/deleteUserData` endpoint.
- [https://getpocket.atlassian.net/browse/OSL-386](https://getpocket.atlassian.net/browse/OSL-386)
=> OSL-386: Execute data deletion from /deleteUserData express endpoint

prisma/migrations/20230427220337_add_list_restoration_details/migration.sql, prisma/migrations/20230501175820_add_restoration_reason_to_list/migration.sql, prisma/schema.prisma, schema-admin.graphql, src/admin/resolvers/fragments.gql.ts, src/admin/resolvers/mutations/ShareableList.integration.ts, src/admin/resolvers/mutations/ShareableList.ts, src/database/mutations/ShareableList.ts, src/database/types.ts, src/snowplow/events.spec.ts
Adding a new optional field to the List obj `listRestorationReason` to contain the reason why a list was restored by a moderator (moderation status from hidden to visible). See [slack thread](https://pocket.slack.com/archives/C04HWMUKLN5/p1682626870569429) here.
* Added optional field to prisma schema.
* Added the field as an optional param to the admin graphQL schema.
* `moderationReason` is now optional on the graph level for the `ModerateShareableInput` type but enforced in the resolver when list is set to hidden.
* `listRestoration` is also optional on the graph level for the `ModerateShareableInput` type but enforced in the resolver when list is set to visible.
* Updated tests.
For now, we will not store historical moderation data in the db, and overwrite the moderation fields if a …
=> OSL-472: adding listRestorationReason field to db, updating resolvers and tests

prisma/schema.prisma, schema-public.graphql, src/database/mutations.ts, src/database/mutations/ShareableListItem.ts, src/database/types.ts, src/public/resolvers/index.ts, src/public/resolvers/mutations/ShareableListItem.integration.ts, src/public/resolvers/mutations/ShareableListItem.ts, src/public/resolvers/mutations/sample-mutations.gql.ts
Adding a new `updateShareableListItems` mutation which accepts an array of shareable list item `sortOrder`. This is for bulk edit/ reorder effort.
- [https://getpocket.atlassian.net/browse/OSL-478](https://getpocket.atlassian.net/browse/OSL-478)
According to this [known issue](https://github.com/prisma/prisma/issues/6862), it is not possible to use the `updateMany` prisma call to update several rows with different values, so using the [transactions API ](https://www.prisma.io/docs/guides/performance-and-optimization/prisma-client-transactions-guide#transaction-api)to perform the bulk update.
=> OSL-478: Adding updateShareableListItems mutation for bulk edit feat

src/database/mutations/ShareableList.ts, src/database/queries/ShareableList.ts, src/public/resolvers/queries/ShareableList.integration.ts, src/test/helpers/createShareableListItemHelper.ts
return listItems by `sortOrder`
- specify fallback sorting by createdAt ascending (which was default)
- https://getpocket.atlassian.net/browse/OSL-425
=> fix(listItem sort): return listItems by sortOrder

schema-shared.graphql, src/public/resolvers/index.ts, src/public/resolvers/mutations/ShareableList.integration.ts, src/public/resolvers/mutations/ShareableListItem.integration.ts, src/public/resolvers/queries/ShareableList.integration.ts, src/shared/fragments.gql.ts, src/shared/resolvers/fields/Item.ts
reference parser Item from shareable list item.
- https://getpocket.atlassian.net/browse/OSL-482
not extending `Item` yet, but we will soon (adding in `ShareableListItem` from the `Item` side).
joining on `itemId`, but we could also use `url`. is there a preference at this point?
=> feat(parser Item): reference parser Item from shareable list item

src/admin/resolvers/index.ts, src/admin/resolvers/queries/ShareableList.integration.ts
Forgot to resolve the `Item` type in the admin graph resolver.
- [https://getpocket.atlassian.net/browse/OSL-502](https://getpocket.atlassian.net/browse/OSL-502)
=> OSL-502: add item property to shareable list item type (for admin graph)

schema-public.graphql, schema-shared.graphql, src/public/resolvers/queries/ShareableList.integration.ts, src/shared/fragments.gql.ts
add listItemNoteVisibility to `shareableListPublic` query
- https://getpocket.atlassian.net/browse/OSL-503
even though they are now equal, kept the `ShareableListPublicProps` and `ShareableListPublicQueryProps` fragments separate, as these may well diverge in the near future.
=> chore(shareableListPublic): add listItemNoteVisibility to query

.aws/.gitignore, .aws/package-lock.json, .aws/package.json, .aws/src/files/nodejs/node_modules/synthetic/index.ts, .aws/src/main.ts, .aws/src/synthetics.ts, .aws/tsconfig.json
Synthetic Alerts skeleton. Has some sane defaults.
Sets up synthetic alert (in vpc) for uptime checks (e.g. http endpoint on get returns 2xx) & "query" checks (e.g. http post on graphql endpoint with graphql sent & jmespath + expected response to validate response).
Removes old alerts from setup (default being load balance 5xx checks, which have failed us in the past).
Long term, the idea is to have this synthetic setup as generic as possible for uptime & graphql checks, then spin up needed synthetics via that config map structure (which just maps to environment variables for the synthetic checks).
Shouldn't block this PR going through, but immediate next steps
=> Infra 1169/synthetic skeleton

schema-admin.graphql, schema-public.graphql, schema-shared.graphql, src/admin/resolvers/fragments.gql.ts, src/admin/resolvers/index.ts, src/admin/resolvers/queries/ShareableList.integration.ts, src/shared/fragments.gql.ts
**Problem:** Curation admin tool (or any client using the admin graph) generates the admin types and uses them to get data. Parser `Item` type generated by the admin tool has `itemId`, `givenUrl` and `normalUrl` required. The shareable lists API only resolves `itemId` on `Item`. Front-end tool complains about type mismatch as it uses the generated types. 
**Solution:** The admin graph does not need `item: Item` returned for shareable list item, so creating an admin type to use specifically for the admin graph. 
- [https://getpocket.atlassian.net/browse/OSL-510](https://getpocket.atlassian.net/browse/OSL-510)
=> OSL-510: adding an admin shareable list item type

schema-shared.graphql, src/public/resolvers/mutations/ShareableList.integration.ts, src/public/resolvers/mutations/ShareableListItem.integration.ts, src/public/resolvers/queries/ShareableList.integration.ts, src/shared/fragments.gql.ts, src/shared/resolvers/fields/Item.ts
use `givenUrl` for Item connection (instead of `itemId`). the current `itemId` connection (we think) is causing issues connecting to an `Item` > `SavedItem`. this is a hopeful fix for that issue.
see [this long slack thread](https://pocket.slack.com/archives/C03QVL4SU/p1684867901864509) for some details.
- https://getpocket.atlassian.net/browse/OSL-528
=> refactor(Item): use givenUrl for Item connection

schema-public.graphql, schema-shared.graphql, src/public/resolvers/index.ts, src/public/resolvers/mutations/ShareableList.integration.ts, src/public/resolvers/mutations/ShareableListItem.integration.ts, src/public/resolvers/queries/ShareableList.integration.ts, src/public/resolvers/queries/sample-queries.gql.ts, src/shared/resolvers/fields/SavedItem.ts, src/snowplow/events.spec.ts, src/test/helpers/createShareableListHelper.ts, src/test/helpers/createShareableListItemHelper.ts
* Extending `SavedItem` type & adding an additional `shareableListTotalCount` property to indicate in how many shareable lists a save is (via `url`). See [slack thread](https://pocket.slack.com/archives/C04HWMUKLN5/p1684804833654229) for discussion.
- [https://getpocket.atlassian.net/browse/OSL-499](https://getpocket.atlassian.net/browse/OSL-499)
=> OSL-499: Extending SavedItem & adding shareableListTotalCount property

lambda/events/index.spec.ts, lambda/events/index.ts
do not throw errors when no lambda handler exists for the event bridge SNS > SQS message type.
- list API sends a bunch of events, only one of which we want to handle in this lambda, so we don't want to error on the others.
didn't think we needed to error or even log when a handler isn't found, as this is going to happen ALL THE TIME now that we're subscribing to list API events.
=> refactor(lambda errors): do not throw errors when no lambda handler

.aws/package-lock.json, .aws/package.json, .aws/src/main.ts, README.md
We're out of the tier 1 alerting period for shareable lists api (agreed to originally to cover period when a lot of media was focused on the new feature).
As such, moving this to tier 2 alerting, which means alert response during business hours only (which translates currently to alerts via email).
=> feat(archive): downgrade from tier1 to tier2 alerting

.aws/src/config/index.ts, .aws/src/main.ts
Creating a new SQS to queue shareable list items for deletion
- [https://getpocket.atlassian.net/browse/OSL-561](https://getpocket.atlassian.net/browse/OSL-561)
=> OSL-561: SQS for batch delete shareable list items

schema-admin.graphql, src/admin/resolvers/fragments.gql.ts, src/admin/resolvers/index.ts, src/shared/fragments.gql.ts
This is part of the foundational refactor rollback. Removes `ShareableListItemAdmin` type from admin schema, updates resolver and tests.
- [https://getpocket.atlassian.net/browse/OSL-573](https://getpocket.atlassian.net/browse/OSL-573)
=> OSL-573: Remove ShareableListItemAdmin type from schema

src/database/types.ts, src/snowplow/events.spec.ts, src/snowplow/events.ts, src/snowplow/types.ts
This is part of the foundational refactor rollback. Adding back the list item metadata to Snowplow type and sending to event bridge.
- [https://getpocket.atlassian.net/browse/OSL-576](https://getpocket.atlassian.net/browse/OSL-576)
=> OSL-576: send list item metadata to Snowplow

.aws/src/config/index.ts, .aws/src/main.ts
remove SQS for queueing items for deletion. a revert of #245.
- part of the shelf stable work
- https://getpocket.atlassian.net/browse/OSL-580
=> chore(rollback): remove SQS for queueing items for deletion

.circleci/scripts/setup_aws.sh, package-lock.json, schema-public.graphql, src/database/mutations/ShareableList.ts, src/public/resolvers/mutations/ShareableList.integration.ts
Blocking the ability to make a list `PUBLIC`. Current `PUBLIC` lists can stay `PUBLIC`, but if switched to `PRIVATE`, can no longer switch back to `PUBLIC`. Commented out relevant tests in case we ever turn back the functionality. 
- [https://getpocket.atlassian.net/browse/OSL-577](https://getpocket.atlassian.net/browse/OSL-577)
=> OSL-577: block ability to make lists public
