Pocket/shareable-lists-api

.aws/src/main.ts, .circleci/config.yml, README.md, catalog-info.yaml, schema.graphql, src/config/index.ts, src/express.ts, src/resolvers.ts, src/sample-queries.gql.ts, src/server.ts
* Added a new project to Sentry: [https://sentry.io/settings/pocket/projects/shareable-lists-api/](https://sentry.io/settings/pocket/projects/shareable-lists-api/)
* Configured Sentry plugin for Apollo Server
* Added new parameters to SSM parameter store for `SENTRY_DSN` for both Dev and Prod
- [https://getpocket.atlassian.net/browse/OSL-139](https://getpocket.atlassian.net/browse/OSL-139)
=> OSL-139: Configuring Sentry & minor refactoring

.circleci/config.yml, package.json
Adding `prisma` to `package.json` and CircleCI config
- [https://getpocket.atlassian.net/browse/OSL-186](https://getpocket.atlassian.net/browse/OSL-186)
=> adding prisma generate & migrate

src/public/resolvers/mutations/ShareableList.integration.ts
Small ticket to assert error codes in `ShareableList` mutation integration test
- [https://getpocket.atlassian.net/browse/OSL-195](https://getpocket.atlassian.net/browse/OSL-195)
=> OSL-195: adding error codes to ShareableList mutation integration test

src/admin/resolvers.ts, src/public/resolvers/index.ts
Keep the new repo up with the latest changes. Updated both public and admin resolvers.
https://getpocket.atlassian.net/browse/OSL-208
=> chore(resolvers): [OSL-208] Use `ISOString` scalar resolver from `apollo-utils`

src/database/mutations/ShareableList.ts, src/public/resolvers/mutations/ShareableList.integration.ts, src/shared/constants.ts
* Enforce list title is max 100 chars
* Enforce list description (if provided) is max 200 chars
- [https://getpocket.atlassian.net/browse/OSL-235](https://getpocket.atlassian.net/browse/OSL-235)
=> OSL-235: put a limit on list title and description

prisma/migrations/20230301174850_listitem_itemid_to_bigint/migration.sql, prisma/schema.prisma, schema-public.graphql, src/public/resolvers/index.ts, src/public/resolvers/mutations/ShareableListItem.integration.ts
accept values larger than Int32 for `itemId`.
- [Slack thread](https://pocket.slack.com/archives/C04HWMUKLN5/p1677690212803599)
- https://getpocket.atlassian.net/browse/OSL-242
=> refactor(itemId): use Float/BigInt for itemId value

.github/CODEOWNERS
Have reviewers assigned to PRs automatically when the latter get created or flipped over to "Ready for review" state.
- https://getpocket.atlassian.net/browse/OSL-204
=> chore(code reviews): [OSL-204] Add automatic assignment of reviewers to repository

prisma/migrations/20230302224820_add_model_for_pilotuser/migration.sql, prisma/schema.prisma
create a prisma model for pilot users.
- https://getpocket.atlassian.net/browse/OSL-247
- kept as simple as possible with a slight eye to the future (`mozillaEmployee` and `createdBy` fields).
=> feat(pilot user db model): add prisma model for pilot user

schema-public.graphql, src/public/resolvers/index.ts, src/public/resolvers/queries/PilotUser.integration.ts, src/public/resolvers/queries/sample-queries.gql.ts
make a more federation friendly query name 😵‍💫 
- https://getpocket.atlassian.net/browse/OSL-248
=> refactor(pilot user query): make the query name more federation friendly

src/snowplow/events.spec.ts, src/snowplow/types.ts
Decided to update the event types to what we see in Snowplow. [Slack thread](https://pocket.slack.com/archives/C03QVL4SU/p1678391147397099) for convo
* [https://getpocket.atlassian.net/browse/OSL-210](https://getpocket.atlassian.net/browse/OSL-210)
=> OSL-210: updating the event type to expected snowplow event type

.aws/package-lock.json, .aws/package.json, .aws/src/main.ts, docker-compose.yml
Adding Redis Cache AWS Infra
- [https://getpocket.atlassian.net/browse/OSL-265](https://getpocket.atlassian.net/browse/OSL-265)
=> OSL-265: Adding Redis Cache AWS Infra

prisma/migrations/20230323171807_add_notes_to_pilotuser/migration.sql, prisma/schema.prisma
add notes field to pilot user table - for a bit more context as we add more pilot users.
- https://getpocket.atlassian.net/browse/OSL-315
=> chore(pilot user): add notes field to pilot user table

src/admin/resolvers/index.ts
Need to resolve the User obj and itemId in the admin resolver.
- [https://getpocket.atlassian.net/browse/OSL-318](https://getpocket.atlassian.net/browse/OSL-318)
=> OSL-318: resolve User obj and itemId in admin resolver

README.md
As above - link to the freshly created instructions page, too.
- unticketed
=> chore(docs): Add instructions to reset data on Dev

schema-public.graphql, src/database/mutations.ts, src/database/mutations/ShareableListItem.ts, src/database/types.ts, src/public/resolvers/index.ts, src/public/resolvers/mutations/ShareableListItem.integration.ts, src/public/resolvers/mutations/ShareableListItem.ts, src/public/resolvers/mutations/sample-mutations.gql.ts
add `updateShareableListItem` mutation w/tests.
- https://getpocket.atlassian.net/browse/OSL-393
=> feat(updateShareableListItem): add mutation and tests

package-lock.json, package.json, src/public/server.ts
add error logging to apollo studio.
[pushed to dev](https://app.circleci.com/pipelines/github/Pocket/shareable-lists-api/1576/workflows/fc94f731-9578-4280-919a-4a98aaa98994) and tested a query and it worked fine.
copied [kat's pattern from list API](https://github.com/Pocket/list-api/pull/751).
- https://getpocket.atlassian.net/browse/OSL-511
=> fix(observability): add error logging to apollo studio

.aws/src/config/index.ts, .aws/src/main.ts, lambda/events/handlers/accountDelete.spec.ts, lambda/events/handlers/accountDelete.ts, lambda/events/handlers/index.ts, lambda/events/handlers/saveDelete.ts
beginnings of save delete handler
- console log for now to verify message format
- https://getpocket.atlassian.net/browse/OSL-520
just logging for now to validate message format/contents.
=> feat(save delete handler): beginnings of save delete handler

lambda/events/handlers/saveDelete.ts
just stop flooding the logs - we are now receiving the data and format is as expected.
=> fix(logging): stop logging save delete events

src/database/types.ts, src/snowplow/events.spec.ts, src/snowplow/events.ts, src/snowplow/types.ts
Stop sending Parser metadata to Snowplow.
-[https://getpocket.atlassian.net/browse/OSL-495]( https://getpocket.atlassian.net/browse/OSL-495)
=> OSL-495: stop sending Parser metadata to Snowplow

src/express.ts, src/public/routes/deleteShareableListItems.integration.ts, src/public/routes/deleteShareableListItems.ts, src/public/routes/deleteUserData.integration.ts, src/public/routes/deleteUserData.ts, src/public/routes/helpers.ts, src/public/routes/index.ts
* Adding `deleteShareableListItems` express endpoint which deletes list items for a given user by `url` (coming from a `SavedItem`)
This endpoint will be called from a lambda function.
- [https://getpocket.atlassian.net/browse/OSL-519](https://getpocket.atlassian.net/browse/OSL-519)
=> OSL-519: adding deleteShareableListItems express endpoint

src/database/mutations/ShareableList.ts, src/database/mutations/ShareableListItem.ts, src/database/types.ts, src/public/resolvers/mutations/ShareableList.integration.ts, src/public/resolvers/mutations/ShareableListItem.integration.ts
bump list `updatedAt` value on all related operations.
- https://getpocket.atlassian.net/browse/OSL-532
=> feat(list): bump list updatedAt value on all related operations

.aws/package-lock.json, .aws/package.json
Update tf modules version. Why? to get some changes to synchecks & dashboards.
Tested in dev.
=> chore(tf upgrade): update to latest pocket/tfmodules

src/express.ts
improve health check by making sure db is reachable
- organized imports bc i can't help myself
Documentation here:
- https://mozilla-hub.atlassian.net/browse/SOCIALPLAT-409
=> chore(healthcheck): improve health check by making sure db is reachable
